[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yes_we_KAN"
version = "0.1.0"
description = "Pytorch pipeline for KAN and FKAN models for temperature forecasting"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "torch>=2.0.0",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.4.0",   
    "tqdm>=4.65.0",
    "tabulate>=0.9.0",
]